#pragma once

// KillerKoala ESP32-S3 DualEye config RevA29.
// Exact target: Waveshare ESP32-S3-DualEye-Touch-LCD-1.28.
// ESP32-S3R8, 16 MB flash, 8 MB OPI PSRAM, two GC9A01A 240x240 LCDs,
// two CST816 touch controllers, ES8311 speaker codec, and ES7210 mic ADC.

#define KOALABLUE_FW_VERSION "0.7.0-dualeye-video-lcd2-primary"
#define COMPANION_NAME "killerkoala"
#define WAKE_WORD "killerkoala"
#define SERIAL_BAUD 115200

#define KOALABLUE_ACTIVE_THEME "jungle_jumanji_eucalyptus"
#define KOALABLUE_THEMES_DIR "firmware/esp32-dualeye/themes"

#define ESP32S3_DUALEYE_EXTERNAL_2G4_ANTENNA 0
#define ESP32S3_DUALEYE_2G4_ANTENNA_MODE "onboard_ceramic_default"
#define ESP32S3_DUALEYE_2G4_ANTENNA_CONNECTOR "onboard ceramic 2.4 GHz antenna"
#define ESP32S3_DUALEYE_2G4_WIRING_PATH "factory onboard ceramic antenna path"
#define ESP32S3_DUALEYE_VENDOR_SELECTOR_REQUIRED 0

#define ESP32S3_DUALEYE_BUILTIN_MIC 1
#define ESP32S3_DUALEYE_MIC_ROLE "Waveshare ES7210 microphone path for KillerKoala wake and short voice-command events"
#define ESP32S3_VOICE_FRONTEND_STACK "ESP32-S3 DualEye local wake/short-command front end + Raspberry Pi AI router"
#define ESP32S3_WAKE_MODEL "killerkoala wake phrase over ESP32-S3 DualEye built-in mic event bridge"
#define ESP32S3_COMMAND_MODEL "short repeatable command phrases bridged over USB CDC serial"
#define ESP32S3_COMMAND_ALIAS_PACK "firmware/esp32-dualeye/voice_commands/killerkoala_multinet_aliases.csv"
#define KILLERKOALA_COMPANION_BRAIN "Raspberry Pi large-vocabulary Australian male cyberpunk companion"
#define KILLERKOALA_RESPONSE_POLICY "anti-repeat rotating Australian terminology; Pi handles complex answers"

#define ENABLE_LOCAL_BLE_SCAN 1
#define ENABLE_KOALA_KOMBAT_WIFI_NODE 1
#define ENABLE_KOALA_KOMBAT_SERIAL_COMMANDS 1
#define ENABLE_MIC_WAKE 1
#define ENABLE_WAKE_WORD_FILTER 1
#define ENABLE_DISPLAY_STUB 0
#define ENABLE_DISPLAY_BOOT_ANIMATION 1
#define ENABLE_AUDIO_SPEAKER 1
#define ENABLE_TOUCH_MENU 1

#define KOALA_KOMBAT_WIFI_SCAN_INTERVAL_MS 15000
#define KOALA_KOMBAT_WIFI_MAX_APS 16
#define KOALA_KOMBAT_WIFI_PASSIVE_SCAN 1

#define DISPLAY_DRIVER "GC9A01A_DUAL"
#define DISPLAY_WIDTH 240
#define DISPLAY_HEIGHT 240
#define DISPLAY_SPI_MISO_PIN 40
#define DISPLAY_SPI_MOSI_PIN 42
#define DISPLAY_SPI_SCLK_PIN 41
#define DISPLAY_SPI_DC_PIN 45
#define DISPLAY_LCD1_CS_PIN 47
#define DISPLAY_LCD1_RESET_PIN 48
#define DISPLAY_LCD1_BACKLIGHT_PIN 46
#define DISPLAY_LCD2_CS_PIN 38
#define DISPLAY_LCD2_RESET_PIN 8
#define DISPLAY_LCD2_BACKLIGHT_PIN 39
#define DISPLAY_LCD1_ROTATION 1
#define DISPLAY_LCD2_ROTATION 3
#define DISPLAY_INVERT_COLOR 1
#define DISPLAY_SPI_SCLK_HZ 80000000UL

#define KOALA_PRIMARY_DISPLAY 2
#define KOALA_PRIMARY_DISPLAY_POSITION "front_right_back_left"
#define KOALA_CRITICAL_UI_PRIMARY_ONLY 1
#define KOALA_TEXT_INPUT_PRIMARY_ONLY 1
#define KOALA_MIRROR_ACTION_ANIMATIONS 1
#define KOALA_ALLOW_MISSING_LCD1 1
#define KOALA_ACTIVE_TOUCH_DISPLAY 2
#define KOALA_EYE_RENDER_FPS 30
#define KOALA_EYE_CANVAS_SIZE 200

#define BOOT_ANIMATION_TOTAL_MS 6000
#define BOOT_ANIMATION_FRAME_MS 33

#define TOUCH_MENU_BACKEND "waveshare_cst816d_lcd2_i2c"
#define TOUCH_MENU_CONTROLLER "CST816D-LCD2"
#define TOUCH_MENU_I2C_ADDR 0x15
#define TOUCH_MENU_I2C_SDA_PIN 3
#define TOUCH_MENU_I2C_SCL_PIN 2
#define TOUCH_MENU_INT_PIN 7
#define TOUCH_MENU_RST_PIN 6
#define TOUCH_MENU_I2C_CLOCK_HZ 400000
#define TOUCH_MENU_POLL_MS 10
#define TOUCH_MENU_SCREEN_W 240
#define TOUCH_MENU_SCREEN_H 240
#define TOUCH_MENU_RAW_MIN_X 0
#define TOUCH_MENU_RAW_MAX_X 239
#define TOUCH_MENU_RAW_MIN_Y 0
#define TOUCH_MENU_RAW_MAX_Y 239
#define TOUCH_MENU_INVERT_X 0
#define TOUCH_MENU_INVERT_Y 0
#define TOUCH_MENU_SWAP_XY 1
#define TOUCH_MENU_ROW_HEIGHT 40
#define TOUCH_MENU_VISIBLE_ROWS 6
#define TOUCH_MENU_LONG_PRESS_MS 500

#define BTN_BACK_PIN -1
#define BTN_SELECT_PIN 0
#define BTN_NEXT_PIN -1
#define BTN_MENU_PIN -1
#define BUTTON_ACTIVE_LOW 1

#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000
#define AUDIO_I2S_MCLK_PIN 12
#define AUDIO_I2S_BCLK_PIN 13
#define AUDIO_I2S_WS_PIN 14
#define AUDIO_I2S_DIN_PIN 15
#define AUDIO_I2S_DOUT_PIN 16
#define AUDIO_CODEC_PA_PIN 9
#define AUDIO_CODEC_I2C_SDA_PIN 11
#define AUDIO_CODEC_I2C_SCL_PIN 10
#define AUDIO_CODEC_ES8311_ADDR 0x18

#ifndef MIC_I2S_BCLK_PIN
#define MIC_I2S_BCLK_PIN AUDIO_I2S_BCLK_PIN
#endif
#ifndef MIC_I2S_WS_PIN
#define MIC_I2S_WS_PIN AUDIO_I2S_WS_PIN
#endif
#ifndef MIC_I2S_DIN_PIN
#define MIC_I2S_DIN_PIN AUDIO_I2S_DIN_PIN
#endif
#define MIC_SAMPLE_RATE_HZ 16000
#define MIC_SAMPLE_BLOCK_SAMPLES 256
#define MIC_WAKE_RMS_THRESHOLD 0.35f
#define MIC_WAKE_COOLDOWN_MS 2500
#define MIC_STATUS_INTERVAL_MS 10000

#ifndef SPEAKER_I2S_BCLK_PIN
#define SPEAKER_I2S_BCLK_PIN AUDIO_I2S_BCLK_PIN
#endif
#ifndef SPEAKER_I2S_WS_PIN
#define SPEAKER_I2S_WS_PIN AUDIO_I2S_WS_PIN
#endif
#ifndef SPEAKER_I2S_DOUT_PIN
#define SPEAKER_I2S_DOUT_PIN AUDIO_I2S_DOUT_PIN
#endif

#define BATTERY_ADC_PIN 1
#define BATTERY_CHARGING_PIN -1

#define BLE_SCAN_SECONDS 3
#define BLE_MAX_RESULTS_PER_CYCLE 16
