[platformio]
default_envs = heltec_mouth

[env:heltec_mouth]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  olikraus/U8g2@^2.36.2
