[platformio]
default_envs = heltec_t114_mouth

[env:heltec_t114_mouth]
platform = nordicnrf52
board = heltec_t114
board_build.variants_dir = variants
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags =
  -D BOARD_HELTEC_T114=1
lib_deps =
  bblanchon/ArduinoJson@^7.0.4
