#pragma once

#include "WVariant.h"

#define USE_LFXO
#define VARIANT_MCK 64000000ul

#define PINS_COUNT 48
#define NUM_DIGITAL_PINS 48
#define NUM_ANALOG_INPUTS 1
#define NUM_ANALOG_OUTPUTS 0

#define PIN_3V3_EN 38
#define BATTERY_PIN 4
#define ADC_MULTIPLIER 4.90F
#define ADC_RESOLUTION 14
#define BATTERY_SENSE_RES 12
#define AREF_VOLTAGE 3.0

#define PIN_SERIAL1_RX 37
#define PIN_SERIAL1_TX 39
#define PIN_SERIAL2_RX 9
#define PIN_SERIAL2_TX 10

#define WIRE_INTERFACES_COUNT 2
#define PIN_WIRE_SDA 26
#define PIN_WIRE_SCL 27
#define PIN_WIRE1_SDA 7
#define PIN_WIRE1_SCL 8

#define SPI_INTERFACES_COUNT 2
#define PIN_SPI_MISO 23
#define PIN_SPI_MOSI 22
#define PIN_SPI_SCK 19
#define PIN_SPI_NSS 24
#define PIN_SPI1_MISO 43
#define PIN_SPI1_MOSI 41
#define PIN_SPI1_SCK 40

#define LED_BUILTIN 35
#define PIN_LED LED_BUILTIN
#define LED_RED LED_BUILTIN
#define LED_BLUE (-1)
#define LED_PIN LED_BUILTIN
#define LED_STATE_ON LOW

#define PIN_NEOPIXEL 14
#define NEOPIXEL_NUM 2

#define PIN_BUTTON1 42
#define BUTTON_PIN PIN_BUTTON1
#define PIN_USER_BTN BUTTON_PIN

#define EXTERNAL_FLASH_DEVICES MX25R1635F
#define EXTERNAL_FLASH_USE_QSPI

#define USE_SX1262
#define LORA_CS 24
#define SX126X_DIO1 20
#define SX126X_BUSY 17
#define SX126X_RESET 25
#define SX126X_DIO2_AS_RF_SWITCH
#define SX126X_DIO3_TCXO_VOLTAGE 1.8

#define PIN_TFT_RST 2
#define PIN_TFT_VDD_CTL 3
#define PIN_TFT_CS 11
#define PIN_TFT_DC 12
#define PIN_TFT_LEDA_CTL 15
