Import("env")

from pathlib import Path
import audioop
import base64
import shutil
import subprocess
import tempfile
import textwrap

project = Path(env.subst("$PROJECT_DIR"))
output = project / "src" / "local_voice_responses_generated.cpp"

# Embedded local replies use Microsoft's natural Australian male William voice as
# the synthesis backend, but the spoken companion identity is always KillerKoala.
# Complex/open-ended responses remain owned by the Raspberry Pi.
VOICE_NAME = "en-AU-WilliamNeural"
PHRASES = (
    ("Wake", "Righto, mate. Killer Koala here. What's the play?"),
    ("Wake", "G'day, legend. Killer Koala is awake."),
    ("Wake", "Too easy, mate. Killer Koala is listening."),
    ("Wake", "Bonza. Killer Koala's on deck."),
    ("Wake", "No dramas, mate. Give Killer Koala the word."),
    ("Wake", "Killer Koala online. Let's get cracking."),
    ("Status", "All Killer Koala systems are sweet as, mate."),
    ("Status", "The canopy is tidy and Killer Koala is ready."),
    ("Status", "She's running clean. No dramas."),
    ("Help", "Say open menu, K one through K eight, or launch any menu item by name."),
    ("Help", "Tell Killer Koala to launch a tool, open a submenu, or use the K keys by voice."),
    ("Greeting", "G'day, mate. Killer Koala is good to hear you."),
    ("Greeting", "Morning, legend. Let's keep the wheels turning."),
    ("Thanks", "No worries, mate."),
    ("Thanks", "Too easy. Happy to help."),
    ("Banter", "Crikey, you do know how to keep a koala busy."),
    ("Banter", "Fair dinkum. The lab is behaving for once."),
    ("Escalate", "Righto, mate. Ask your question and Killer Koala will send it to the big brain."),
)

edge_tts = shutil.which("edge-tts")
ffmpeg = shutil.which("ffmpeg")
if not edge_tts or not ffmpeg:
    raise RuntimeError(
        "ESP32 Australian voice generation requires edge-tts and ffmpeg. "
        "Install edge-tts==7.2.8 and ffmpeg before building firmware."
    )

clips = []
with tempfile.TemporaryDirectory(prefix="koalabyte-killerkoala-voice-") as temp:
    root = Path(temp)
    for index, (category, text) in enumerate(PHRASES):
        media = root / f"clip-{index}.mp3"
        raw = root / f"clip-{index}.raw"
        subprocess.run(
            [
                edge_tts,
                "--voice",
                VOICE_NAME,
                "--rate=+4%",
                "--volume=+24%",
                "--pitch=-2Hz",
                "--text",
                text,
                "--write-media",
                str(media),
            ],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
            text=True,
            timeout=45,
        )
        subprocess.run(
            [
                ffmpeg,
                "-hide_banner",
                "-loglevel",
                "error",
                "-y",
                "-i",
                str(media),
                "-af",
                "highpass=f=75,lowpass=f=3800,loudnorm=I=-12.5:LRA=6:TP=-0.8",
                "-ar",
                "8000",
                "-ac",
                "1",
                "-f",
                "s16le",
                str(raw),
            ],
            check=True,
            timeout=45,
        )
        pcm = raw.read_bytes()
        mulaw = audioop.lin2ulaw(pcm, 2)
        clips.append(
            {
                "category": category,
                "text": text,
                "samples": len(pcm) // 2,
                "base64": base64.b64encode(mulaw).decode("ascii"),
            }
        )

lines = [
    "// Generated by scripts/generate_local_voice_responses.py.",
    "// Voice backend: en-AU-WilliamNeural; identity: KillerKoala. Do not edit by hand.",
    '#include "local_voice_responses.h"',
    "#include <mbedtls/base64.h>",
    '#include "dualeye_audio.h"',
    "",
    "namespace {",
    "struct LocalVoiceClip {",
    "  LocalVoiceCategory category;",
    "  const char *text;",
    "  const char *mulawBase64;",
    "  uint32_t sourceSamples;",
    "};",
    "",
]

for index, clip in enumerate(clips):
    lines.append(f"static const char kClip{index}[] PROGMEM =")
    chunks = textwrap.wrap(clip["base64"], 112)
    for chunk_index, chunk in enumerate(chunks):
        suffix = ";" if chunk_index == len(chunks) - 1 else ""
        lines.append(f'    "{chunk}"{suffix}')
    lines.append("")

lines.append("static const LocalVoiceClip kClips[] = {")
for index, clip in enumerate(clips):
    escaped = clip["text"].replace("\\", "\\\\").replace('"', '\\"')
    lines.append(
        f'  {{LocalVoiceCategory::{clip["category"]}, "{escaped}", '
        f'kClip{index}, {clip["samples"]}U}},'
    )
lines.extend(
    [
        "};",
        "",
        "uint8_t lastChoice[static_cast<uint8_t>(LocalVoiceCategory::Count)] = {",
        "    255, 255, 255, 255, 255, 255, 255};",
        "",
        "int16_t decodeMuLaw(uint8_t value) {",
        "  value = static_cast<uint8_t>(~value);",
        "  const int sign = value & 0x80U;",
        "  const int exponent = (value >> 4U) & 0x07U;",
        "  const int mantissa = value & 0x0FU;",
        "  int sample = ((mantissa << 3) + 0x84) << exponent;",
        "  sample -= 0x84;",
        "  return static_cast<int16_t>(sign ? -sample : sample);",
        "}",
        "",
        "bool playClip(const LocalVoiceClip &clip) {",
        "  if (!dualEyeSpeakerReady()) return false;",
        "  constexpr size_t kBase64Block = 256;",
        "  unsigned char decoded[192];",
        "  int16_t pcm16k[384];",
        "  size_t produced8k = 0;",
        "  const size_t encodedLength = strlen(clip.mulawBase64);",
        "  for (size_t offset = 0; offset < encodedLength; offset += kBase64Block) {",
        "    size_t take = min(kBase64Block, encodedLength - offset);",
        "    take -= take % 4;",
        "    if (!take) break;",
        "    size_t decodedLength = 0;",
        "    if (mbedtls_base64_decode(",
        "            decoded, sizeof(decoded), &decodedLength,",
        "            reinterpret_cast<const unsigned char *>(clip.mulawBase64 + offset),",
        "            take) != 0) {",
        "      dualEyeAudioStopPlayback();",
        "      return false;",
        "    }",
        "    size_t outCount = 0;",
        "    for (size_t index = 0;",
        "         index < decodedLength && produced8k < clip.sourceSamples; ++index) {",
        "      const int16_t sample = decodeMuLaw(decoded[index]);",
        "      pcm16k[outCount++] = sample;",
        "      pcm16k[outCount++] = sample;",
        "      ++produced8k;",
        "    }",
        "    if (outCount && !dualEyeAudioWriteMono16(pcm16k, outCount)) {",
        "      dualEyeAudioStopPlayback();",
        "      return false;",
        "    }",
        "  }",
        "  dualEyeAudioStopPlayback();",
        "  return produced8k > 0;",
        "}",
        "}  // namespace",
        "",
        "size_t localVoiceResponseCount(LocalVoiceCategory category) {",
        "  size_t count = 0;",
        "  for (const auto &clip : kClips) {",
        "    if (clip.category == category) ++count;",
        "  }",
        "  return count;",
        "}",
        "",
        "bool localVoicePlayResponse(LocalVoiceCategory category,",
        "                            const char **selectedText) {",
        "  uint8_t candidates[16];",
        "  uint8_t count = 0;",
        "  for (uint8_t index = 0; index < sizeof(kClips) / sizeof(kClips[0]);",
        "       ++index) {",
        "    if (kClips[index].category == category && count < sizeof(candidates)) {",
        "      candidates[count++] = index;",
        "    }",
        "  }",
        "  if (!count) return false;",
        "  const uint8_t categoryIndex = static_cast<uint8_t>(category);",
        "  uint8_t choice = static_cast<uint8_t>(esp_random() % count);",
        "  if (count > 1 && choice == lastChoice[categoryIndex]) {",
        "    choice = static_cast<uint8_t>((choice + 1U) % count);",
        "  }",
        "  lastChoice[categoryIndex] = choice;",
        "  const LocalVoiceClip &clip = kClips[candidates[choice]];",
        "  if (selectedText) *selectedText = clip.text;",
        "  return playClip(clip);",
        "}",
        "",
    ]
)

content = "\n".join(lines)
if not output.exists() or output.read_text(encoding="utf-8") != content:
    output.write_text(content, encoding="utf-8")
print(
    f"Generated {len(clips)} ESP32 KillerKoala Australian response clips "
    f"({sum(len(clip['base64']) for clip in clips)} base64 characters)"
)
