Import("env")

from pathlib import Path
import audioop
import base64
import shutil
import subprocess
import tempfile
import textwrap

project = Path(env.subst("$PROJECT_DIR"))
output = project / "src" / "local_voice_responses_generated.cpp"

# Small, intentionally repetitive on-device bank. Complex or open-ended replies
# are routed to the Raspberry Pi after the explicit "ask the AI" command.
PHRASES = (
    ("Wake", "Killer Koala is live and ready."),
    ("Wake", "Happy hunting, mate."),
    ("Wake", "Righto, mate. I am listening."),
    ("Wake", "Killer Koala online. What is the play?"),
    ("Wake", "Bonza. The claws are awake."),
    ("Wake", "Too easy. Give me the word."),
    ("Status", "All systems tidy, mate."),
    ("Status", "Eyes up, audio ready, and no dramas."),
    ("Status", "The little blue beast is running clean."),
    ("Help", "I can answer the basics, or send the heavy work to the Pi."),
    ("Help", "Ask for status, help, a menu action, or say ask the AI."),
    ("Greeting", "G day, mate. The canopy is awake."),
    ("Greeting", "Morning, legend. Let us keep it tidy."),
    ("Thanks", "No dramas, mate."),
    ("Thanks", "Too easy. That is what I am here for."),
    ("Banter", "Crikey, you do know how to keep a koala busy."),
    ("Banter", "Fair dinkum. The lab is behaving for once."),
    ("Escalate", "Go on, mate. I will send the next question to the big brain."),
)

espeak = shutil.which("espeak-ng") or shutil.which("espeak")
ffmpeg = shutil.which("ffmpeg")
if not espeak or not ffmpeg:
    raise RuntimeError(
        "ESP32 local voice generation requires espeak/espeak-ng and ffmpeg. "
        "Install both tools before building firmware."
    )

clips = []
with tempfile.TemporaryDirectory(prefix="koalabyte-local-voice-") as temp:
    root = Path(temp)
    for index, (category, text) in enumerate(PHRASES):
        wav = root / f"clip-{index}.wav"
        raw = root / f"clip-{index}.raw"
        subprocess.run(
            [
                espeak,
                "-v",
                "en-au+m3",
                "-s",
                "165",
                "-p",
                "38",
                "-a",
                "170",
                "-w",
                str(wav),
                text,
            ],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        subprocess.run(
            [
                ffmpeg,
                "-hide_banner",
                "-loglevel",
                "error",
                "-y",
                "-i",
                str(wav),
                "-ar",
                "8000",
                "-ac",
                "1",
                "-f",
                "s16le",
                str(raw),
            ],
            check=True,
        )
        pcm = raw.read_bytes()
        mulaw = audioop.lin2ulaw(pcm, 2)
        clips.append(
            {
                "category": category,
                "text": text,
                "samples": len(pcm) // 2,
                "base64": base64.b64encode(mulaw).decode("ascii"),
            }
        )

lines = [
    "// Generated by scripts/generate_local_voice_responses.py.",
    "// Do not edit this file by hand.",
    '#include "local_voice_responses.h"',
    "#include <mbedtls/base64.h>",
    '#include "dualeye_audio.h"',
    "",
    "namespace {",
    "struct LocalVoiceClip {",
    "  LocalVoiceCategory category;",
    "  const char *text;",
    "  const char *mulawBase64;",
    "  uint32_t sourceSamples;",
    "};",
    "",
]

for index, clip in enumerate(clips):
    lines.append(f"static const char kClip{index}[] PROGMEM =")
    chunks = textwrap.wrap(clip["base64"], 112)
    for chunk_index, chunk in enumerate(chunks):
        suffix = ";" if chunk_index == len(chunks) - 1 else ""
        lines.append(f'    "{chunk}"{suffix}')
    lines.append("")

lines.append("static const LocalVoiceClip kClips[] = {")
for index, clip in enumerate(clips):
    escaped = clip["text"].replace("\\", "\\\\").replace('"', '\\"')
    lines.append(
        f'  {{LocalVoiceCategory::{clip["category"]}, "{escaped}", '
        f'kClip{index}, {clip["samples"]}U}},'
    )
lines.extend(
    [
        "};",
        "",
        "uint8_t lastChoice[static_cast<uint8_t>(LocalVoiceCategory::Count)] = {",
        "    255, 255, 255, 255, 255, 255, 255};",
        "",
        "int16_t decodeMuLaw(uint8_t value) {",
        "  value = static_cast<uint8_t>(~value);",
        "  const int sign = value & 0x80U;",
        "  const int exponent = (value >> 4U) & 0x07U;",
        "  const int mantissa = value & 0x0FU;",
        "  int sample = ((mantissa << 3) + 0x84) << exponent;",
        "  sample -= 0x84;",
        "  return static_cast<int16_t>(sign ? -sample : sample);",
        "}",
        "",
        "bool playClip(const LocalVoiceClip &clip) {",
        "  if (!dualEyeSpeakerReady()) return false;",
        "  constexpr size_t kBase64Block = 256;",
        "  unsigned char decoded[192];",
        "  int16_t pcm16k[384];",
        "  size_t produced8k = 0;",
        "  const size_t encodedLength = strlen(clip.mulawBase64);",
        "  for (size_t offset = 0; offset < encodedLength; offset += kBase64Block) {",
        "    size_t take = min(kBase64Block, encodedLength - offset);",
        "    take -= take % 4;",
        "    if (!take) break;",
        "    size_t decodedLength = 0;",
        "    if (mbedtls_base64_decode(",
        "            decoded, sizeof(decoded), &decodedLength,",
        "            reinterpret_cast<const unsigned char *>(clip.mulawBase64 + offset),",
        "            take) != 0) {",
        "      dualEyeAudioStopPlayback();",
        "      return false;",
        "    }",
        "    size_t outCount = 0;",
        "    for (size_t index = 0;",
        "         index < decodedLength && produced8k < clip.sourceSamples; ++index) {",
        "      const int16_t sample = decodeMuLaw(decoded[index]);",
        "      pcm16k[outCount++] = sample;",
        "      pcm16k[outCount++] = sample;",
        "      ++produced8k;",
        "    }",
        "    if (outCount && !dualEyeAudioWriteMono16(pcm16k, outCount)) {",
        "      dualEyeAudioStopPlayback();",
        "      return false;",
        "    }",
        "  }",
        "  dualEyeAudioStopPlayback();",
        "  return produced8k > 0;",
        "}",
        "}  // namespace",
        "",
        "size_t localVoiceResponseCount(LocalVoiceCategory category) {",
        "  size_t count = 0;",
        "  for (const auto &clip : kClips) {",
        "    if (clip.category == category) ++count;",
        "  }",
        "  return count;",
        "}",
        "",
        "bool localVoicePlayResponse(LocalVoiceCategory category,",
        "                            const char **selectedText) {",
        "  uint8_t candidates[16];",
        "  uint8_t count = 0;",
        "  for (uint8_t index = 0; index < sizeof(kClips) / sizeof(kClips[0]);",
        "       ++index) {",
        "    if (kClips[index].category == category && count < sizeof(candidates)) {",
        "      candidates[count++] = index;",
        "    }",
        "  }",
        "  if (!count) return false;",
        "  const uint8_t categoryIndex = static_cast<uint8_t>(category);",
        "  uint8_t choice = static_cast<uint8_t>(esp_random() % count);",
        "  if (count > 1 && choice == lastChoice[categoryIndex]) {",
        "    choice = static_cast<uint8_t>((choice + 1U) % count);",
        "  }",
        "  lastChoice[categoryIndex] = choice;",
        "  const LocalVoiceClip &clip = kClips[candidates[choice]];",
        "  if (selectedText) *selectedText = clip.text;",
        "  return playClip(clip);",
        "}",
        "",
    ]
)

content = "\n".join(lines)
if not output.exists() or output.read_text(encoding="utf-8") != content:
    output.write_text(content, encoding="utf-8")
print(
    f"Generated {len(clips)} ESP32 local response clips "
    f"({sum(len(clip['base64']) for clip in clips)} base64 characters)"
)
