#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
T114_2G4_ANTENNA="${T114_2G4_ANTENNA:-connector}"
T114_ANTENNA_SWITCH_OVERLAY="${T114_ANTENNA_SWITCH_OVERLAY:-}"
T114_ANTENNA_SWITCH_GPIO_CONTROLLER="${T114_ANTENNA_SWITCH_GPIO_CONTROLLER:-}"
T114_ANTENNA_SWITCH_GPIO_PIN="${T114_ANTENNA_SWITCH_GPIO_PIN:-}"
T114_ANTENNA_SWITCH_ACTIVE="${T114_ANTENNA_SWITCH_ACTIVE:-high}"
T114_ANTENNA_SWITCH_DEFAULT_STATE="${T114_ANTENNA_SWITCH_DEFAULT_STATE:-on}"
T114_ANTENNA_STATUS_PATH="${T114_ANTENNA_STATUS_PATH:-${REPO_ROOT}/logs/t114_2g4_antenna_status.json}"
GENERATED_OVERLAY="${GENERATED_OVERLAY:-${REPO_ROOT}/build/overlays/t114_external_2g4_antenna.overlay}"
PRINT_EXPORT=0
CHECK_ONLY=0

usage() {
  cat <<'EOF'
KoalaByte Blue Heltec T114 nRF52840 external 2.4 GHz antenna setup

Usage:
  bash scripts/configure_t114_2g4_antenna.sh
  T114_2G4_ANTENNA=connector bash scripts/configure_t114_2g4_antenna.sh
  T114_2G4_ANTENNA=external bash scripts/configure_t114_2g4_antenna.sh --print-export
  T114_ANTENNA_SWITCH_OVERLAY=/path/to/board_external_2g4.overlay bash scripts/configure_t114_2g4_antenna.sh --print-export

Important:
  The requested default is a physical connection: use the Heltec board's 2.4 GHz antenna connector.
  Do not attach the LoRa antenna to the 2.4 GHz connector.
  Do not guess an RF-switch pin. Use the exact Heltec T114/Tracker V2 schematic or board DTS before setting a GPIO overlay.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --print-export) PRINT_EXPORT=1 ;;
    --check-only) CHECK_ONLY=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
  shift
done

cd "${REPO_ROOT}"
mkdir -p "$(dirname "${T114_ANTENNA_STATUS_PATH}")" "$(dirname "${GENERATED_OVERLAY}")"

json_escape() {
  python3 - <<'PY' "$1"
import json, sys
print(json.dumps(sys.argv[1]))
PY
}

write_status() {
  local status="$1"
  local reason="$2"
  local overlay="$3"
  local applied="$4"
  local connector="$5"
  cat > "${T114_ANTENNA_STATUS_PATH}" <<JSON
{
  "antenna_request": $(json_escape "${T114_2G4_ANTENNA}"),
  "status": $(json_escape "${status}"),
  "reason": $(json_escape "${reason}"),
  "physical_connection": $(json_escape "${connector}"),
  "overlay": $(json_escape "${overlay}"),
  "overlay_should_be_applied": ${applied},
  "gpio_controller": $(json_escape "${T114_ANTENNA_SWITCH_GPIO_CONTROLLER}"),
  "gpio_pin": $(json_escape "${T114_ANTENNA_SWITCH_GPIO_PIN}"),
  "gpio_active": $(json_escape "${T114_ANTENNA_SWITCH_ACTIVE}"),
  "default_state": $(json_escape "${T114_ANTENNA_SWITCH_DEFAULT_STATE}"),
  "requires_hardware_validation": true,
  "validation_doc": "docs/T114_EXTERNAL_2G4_ANTENNA.md",
  "updated_at": $(date +%s)
}
JSON
}

case "${T114_2G4_ANTENNA}" in
  connector|CONNECTOR|Connector|external|EXTERNAL|External|hardware|HARDWARE|Hardware) ;;
  onboard|ONBOARD|Onboard|disabled|DISABLED|Disabled)
    write_status "disabled" "External 2.4 GHz antenna connector path disabled by T114_2G4_ANTENNA=${T114_2G4_ANTENNA}." "" false "not requested"
    [[ "${PRINT_EXPORT}" == "1" ]] && echo ""
    exit 0
    ;;
  *) echo "Unsupported T114_2G4_ANTENNA=${T114_2G4_ANTENNA}. Use connector, external, hardware, onboard, or disabled." >&2; exit 2 ;;
esac

if [[ -n "${T114_ANTENNA_SWITCH_OVERLAY}" ]]; then
  if [[ ! -f "${T114_ANTENNA_SWITCH_OVERLAY}" ]]; then
    echo "T114_ANTENNA_SWITCH_OVERLAY does not exist: ${T114_ANTENNA_SWITCH_OVERLAY}" >&2
    write_status "overlay_missing" "Custom overlay path was provided but does not exist." "${T114_ANTENNA_SWITCH_OVERLAY}" false "attach 2.4 GHz antenna to board 2.4 GHz antenna connector"
    exit 1
  fi
  write_status "custom_overlay" "Using user-supplied Zephyr overlay for a confirmed RF switch; physical antenna still connects to the board's 2.4 GHz antenna connector." "${T114_ANTENNA_SWITCH_OVERLAY}" true "attach 2.4 GHz antenna to board 2.4 GHz antenna connector"
  [[ "${PRINT_EXPORT}" == "1" ]] && echo "${T114_ANTENNA_SWITCH_OVERLAY}"
  exit 0
fi

if [[ -n "${T114_ANTENNA_SWITCH_GPIO_CONTROLLER}" && -n "${T114_ANTENNA_SWITCH_GPIO_PIN}" ]]; then
  active_flag="GPIO_ACTIVE_HIGH"
  if [[ "${T114_ANTENNA_SWITCH_ACTIVE}" == "low" || "${T114_ANTENNA_SWITCH_ACTIVE}" == "LOW" ]]; then
    active_flag="GPIO_ACTIVE_LOW"
  fi
  cat > "${GENERATED_OVERLAY}" <<EOF
/* Auto-generated by scripts/configure_t114_2g4_antenna.sh.
 * Validate against the exact Heltec board schematic before use.
 */
/ {
    koalabyte_t114_2g4_antenna {
        compatible = "gpio-leds";
        ext_2g4_ant_select: ext_2g4_ant_select {
            gpios = <&${T114_ANTENNA_SWITCH_GPIO_CONTROLLER} ${T114_ANTENNA_SWITCH_GPIO_PIN} ${active_flag}>;
            label = "KOALABYTE_T114_EXT_2G4_ANT_CONNECTOR_SELECT";
            default-state = "${T114_ANTENNA_SWITCH_DEFAULT_STATE}";
        };
    };
};
EOF
  write_status "generated_overlay" "Generated Zephyr overlay to drive a confirmed RF-switch GPIO toward the external 2.4 GHz antenna connector path." "${GENERATED_OVERLAY}" true "attach 2.4 GHz antenna to board 2.4 GHz antenna connector"
  [[ "${PRINT_EXPORT}" == "1" ]] && echo "${GENERATED_OVERLAY}"
  exit 0
fi

write_status "connector_physical" "Configured for physical external 2.4 GHz antenna use: attach the 2.4 GHz antenna to the Heltec board's 2.4 GHz antenna connector. No firmware overlay is applied because no confirmed RF-switch GPIO was provided." "" false "attach 2.4 GHz antenna to board 2.4 GHz antenna connector"
[[ "${PRINT_EXPORT}" == "1" ]] && echo ""
