#!/usr/bin/env bash
set -euo pipefail

# KoalaByte Blue Heltec T114 USB serial detection helper.
# David's live board enumerates as:
#   /dev/serial/by-id/usb_Heltec_HT_n5262_F0E6F99E30161F35-if00 -> ../../ttyACM0
# Prefer that exact by-id path, then fall back to broader Heltec/n5262 matches,
# then KoalaByte udev aliases, then ttyACM0.

KOALABYTE_HELTEC_T114_USB_ID="${KOALABYTE_HELTEC_T114_USB_ID:-usb_Heltec_HT_n5262_F0E6F99E30161F35-if00}"
KOALABYTE_HELTEC_T114_BY_ID="${KOALABYTE_HELTEC_T114_BY_ID:-/dev/serial/by-id/${KOALABYTE_HELTEC_T114_USB_ID}}"
KOALABYTE_HELTEC_DEVICE_ENV="${KOALABYTE_HELTEC_DEVICE_ENV:-/etc/koalabyte-blue/device.env}"

resolve_heltec_t114_port() {
  local candidate=""

  if [[ -n "${KOALABYTE_HELTEC_USB_PORT:-}" && -e "${KOALABYTE_HELTEC_USB_PORT}" ]]; then
    printf '%s\n' "${KOALABYTE_HELTEC_USB_PORT}"
    return 0
  fi

  if [[ -n "${HELTEC_PORT:-}" && -e "${HELTEC_PORT}" ]]; then
    printf '%s\n' "${HELTEC_PORT}"
    return 0
  fi

  if [[ -e "${KOALABYTE_HELTEC_T114_BY_ID}" ]]; then
    printf '%s\n' "${KOALABYTE_HELTEC_T114_BY_ID}"
    return 0
  fi

  candidate="$(ls /dev/serial/by-id/* 2>/dev/null | grep -Eim1 'Heltec|HT[_-]?n5262|n5262|T114' || true)"
  if [[ -n "${candidate}" && -e "${candidate}" ]]; then
    printf '%s\n' "${candidate}"
    return 0
  fi

  for candidate in /dev/koalabyte-heltec-t114 /dev/koalabyte-heltec /dev/ttyACM0 /dev/ttyACM1 /dev/ttyUSB0 /dev/ttyUSB1; do
    if [[ -e "${candidate}" ]]; then
      printf '%s\n' "${candidate}"
      return 0
    fi
  done

  return 1
}

write_heltec_t114_env_file() {
  local port="$1"
  local env_path="${2:-${KOALABYTE_HELTEC_DEVICE_ENV}}"
  local env_dir
  env_dir="$(dirname "${env_path}")"

  if [[ "${EUID}" -eq 0 ]]; then
    mkdir -p "${env_dir}"
    cat > "${env_path}" <<EOF
# Generated by scripts/detect_heltec_t114.sh
HELTEC_PORT=${port}
KOALABYTE_HELTEC_USB_PORT=${port}
KOALABYTE_PRIMARY_BLE_PORT=${port}
HELTEC_MODEL=Heltec_T114
HELTEC_USB_ID=${KOALABYTE_HELTEC_T114_USB_ID}
KOALABYTE_HELTEC_T114_BY_ID=${KOALABYTE_HELTEC_T114_BY_ID}
EOF
  elif command -v sudo >/dev/null 2>&1; then
    sudo mkdir -p "${env_dir}"
    cat <<EOF | sudo tee "${env_path}" >/dev/null
# Generated by scripts/detect_heltec_t114.sh
HELTEC_PORT=${port}
KOALABYTE_HELTEC_USB_PORT=${port}
KOALABYTE_PRIMARY_BLE_PORT=${port}
HELTEC_MODEL=Heltec_T114
HELTEC_USB_ID=${KOALABYTE_HELTEC_T114_USB_ID}
KOALABYTE_HELTEC_T114_BY_ID=${KOALABYTE_HELTEC_T114_BY_ID}
EOF
  else
    return 1
  fi
}

print_heltec_t114_exports() {
  local port="$1"
  printf "export HELTEC_PORT='%s'\n" "${port}"
  printf "export KOALABYTE_HELTEC_USB_PORT='%s'\n" "${port}"
  printf "export KOALABYTE_PRIMARY_BLE_PORT='%s'\n" "${port}"
  printf "export HELTEC_USB_ID='%s'\n" "${KOALABYTE_HELTEC_T114_USB_ID}"
  printf "export KOALABYTE_HELTEC_T114_BY_ID='%s'\n" "${KOALABYTE_HELTEC_T114_BY_ID}"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  MODE="detect"
  case "${1:-}" in
    --env) MODE="env" ;;
    --write-device-env) MODE="write" ;;
    --check-only|"") MODE="detect" ;;
    -h|--help)
      cat <<'EOF'
Usage:
  bash scripts/detect_heltec_t114.sh
  bash scripts/detect_heltec_t114.sh --env
  bash scripts/detect_heltec_t114.sh --write-device-env

Detects the KoalaByte Blue Heltec T114 USB serial port. Preferred live-board path:
  /dev/serial/by-id/usb_Heltec_HT_n5262_F0E6F99E30161F35-if00
Fallback:
  /dev/ttyACM0
EOF
      exit 0
      ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac

  if ! HELTEC_T114_PORT="$(resolve_heltec_t114_port)"; then
    echo "Heltec T114 not detected. Plug it in with a USB data cable and try again." >&2
    exit 1
  fi

  case "${MODE}" in
    env)
      print_heltec_t114_exports "${HELTEC_T114_PORT}"
      ;;
    write)
      write_heltec_t114_env_file "${HELTEC_T114_PORT}"
      echo "Heltec T114 device env written to ${KOALABYTE_HELTEC_DEVICE_ENV}: ${HELTEC_T114_PORT}"
      ;;
    detect)
      echo "Heltec T114 detected at: ${HELTEC_T114_PORT}"
      ;;
  esac
fi
