#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import time
from pathlib import Path
from typing import Iterable

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_DIR = REPO_ROOT / "logs" / "preflight"

STABLE_PATHS = {
    "primary_ble": "/dev/koalabyte-heltec",
    "heltec": "/dev/koalabyte-heltec",
    "nrf_ble": "/dev/koalabyte-nrf-ble",  # legacy external dongle alias only
    "esp32_eyes": "/dev/koalabyte-esp32-eyes",
}

SERIAL_PATTERNS = [
    "/dev/serial/by-id/*",
    "/dev/ttyACM*",
    "/dev/ttyUSB*",
    "/dev/cu.usbmodem*",
    "/dev/cu.usbserial*",
]

HINTS = {
    "primary_ble": ("koalabyte-heltec", "heltec", "t114", "ht-n5262", "wireless_tracker", "wireless-tracker", "nrf52840"),
    "heltec": ("koalabyte-heltec", "heltec", "t114", "ht-n5262", "wireless_tracker", "wireless-tracker", "nrf52840"),
    "nrf_ble": ("koalabyte-nrf-ble", "nrf52840", "pca10059", "nordic", "adafruit", "jlink"),
    "esp32_eyes": ("koalabyte-esp32-eyes", "esp32", "esp32-s3", "espressif", "cp210", "ch340", "wchusb", "usb-serial"),
}


def run(args: list[str], timeout: float = 3.0) -> dict[str, object]:
    try:
        p = subprocess.run(args, capture_output=True, text=True, timeout=timeout, check=False)
        return {"command": args, "returncode": p.returncode, "stdout": p.stdout.strip(), "stderr": p.stderr.strip()}
    except FileNotFoundError as exc:
        return {"command": args, "returncode": 127, "stdout": "", "stderr": str(exc)}
    except subprocess.TimeoutExpired:
        return {"command": args, "returncode": 124, "stdout": "", "stderr": "command timed out"}


def unique_paths(paths: Iterable[Path]) -> list[Path]:
    seen: set[str] = set()
    out: list[Path] = []
    for path in paths:
        key = str(path)
        if key not in seen:
            seen.add(key)
            out.append(path)
    return out


def serial_candidates() -> list[dict[str, str]]:
    paths: list[Path] = []
    for pattern in SERIAL_PATTERNS:
        paths.extend(sorted(Path("/").glob(pattern.lstrip("/"))))
    entries = []
    for path in unique_paths(paths):
        try:
            resolved = str(path.resolve())
        except OSError:
            resolved = str(path)
        label = f"{path} {resolved}".lower()
        entries.append({"path": str(path), "resolved": resolved, "label": label})
    return entries


def choose_port(entries: list[dict[str, str]], role: str, avoid: set[str]) -> str:
    stable = STABLE_PATHS.get(role, "")
    if stable and Path(stable).exists():
        return stable

    hints = HINTS[role]
    scored: list[tuple[int, str]] = []
    for entry in entries:
        path = entry["path"]
        resolved = entry["resolved"]
        label = entry["label"]
        if path in avoid or resolved in avoid:
            continue
        score = 0
        if path.startswith("/dev/serial/by-id"):
            score += 20
        for hint in hints:
            if hint in label:
                score += 10
        if role == "esp32_eyes" and ("ttyusb" in label or "usbserial" in label):
            score += 3
        if role in {"primary_ble", "heltec", "nrf_ble"} and ("ttyacm" in label or "usbmodem" in label):
            score += 3
        if score:
            scored.append((score, path))
    if not scored:
        return ""
    scored.sort(key=lambda item: (-item[0], item[1]))
    return scored[0][1]


def ip_link_exists(interface: str) -> bool:
    return run(["ip", "link", "show", interface])["returncode"] == 0


def write_env(path: Path, values: dict[str, str]) -> None:
    lines = ["# Generated by scripts/discover_koalabyte_ports.py"]
    for key, value in values.items():
        if value:
            safe = value.replace("'", "'\\''")
            lines.append(f"export {key}='{safe}'")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def resolve_profile(profile: str) -> str:
    if profile == "auto":
        return "heltec"
    return profile


def discover(profile: str) -> dict[str, object]:
    profile = resolve_profile(profile)
    entries = serial_candidates()
    avoid: set[str] = set()

    if profile == "heltec":
        heltec = choose_port(entries, "heltec", avoid)
        if heltec:
            avoid.add(heltec)
        primary_ble = heltec
        legacy_nrf = choose_port(entries, "nrf_ble", avoid)
    else:
        legacy_nrf = choose_port(entries, "nrf_ble", avoid)
        if legacy_nrf:
            avoid.add(legacy_nrf)
        heltec = choose_port(entries, "heltec", avoid)
        primary_ble = legacy_nrf or heltec

    if legacy_nrf:
        avoid.add(legacy_nrf)
    if heltec:
        avoid.add(heltec)
    esp32 = choose_port(entries, "esp32_eyes", avoid)

    can_interface = os.environ.get("CAN_INTERFACE", "can0")
    vcan_interface = os.environ.get("VCAN_INTERFACE", "vcan0")

    env = {
        "KOALABYTE_PRIMARY_BLE_PORT": primary_ble,
        "KOALABYTE_PRIMARY_BLE_SOURCE": "heltec-t114-nrf52840" if profile == "heltec" else "legacy-nrf52840-dongle",
        "KOALABYTE_HELTEC_USB_PORT": heltec,
        "HELTEC_PORT": heltec,
        # Backward-compatible aliases. In the Heltec Edition these point at the Heltec T114 onboard nRF52840.
        "KOALABYTE_NRF_BLE_PORT": primary_ble,
        "NRF_BLE_PORT": primary_ble,
        "KOALABYTE_ESP32_FACE_PORT": esp32,
        "ESP32_PORT": esp32,
        "CAN_INTERFACE": can_interface,
        "CAN_BITRATE": os.environ.get("CAN_BITRATE", "500000"),
        "VCAN_INTERFACE": vcan_interface,
    }

    return {
        "profile": profile,
        "timestamp": time.time(),
        "serial_candidates": entries,
        "stable_paths": STABLE_PATHS,
        "ports": {
            "primary_ble": primary_ble,
            "primary_ble_source": env["KOALABYTE_PRIMARY_BLE_SOURCE"],
            "heltec": heltec,
            "legacy_nrf_ble": legacy_nrf,
            "esp32_eyes": esp32,
            "can_interface": can_interface,
            "can_present": ip_link_exists(can_interface),
            "vcan_interface": vcan_interface,
            "vcan_present": ip_link_exists(vcan_interface),
        },
        "env": env,
        "commands": {
            "lsusb": run(["lsusb"]),
            "ip_link": run(["ip", "link"]),
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Discover KoalaByte Blue V2 Heltec Edition USB/CAN ports and write stable runtime env files.")
    parser.add_argument("--profile", choices=["main", "heltec", "auto"], default="heltec")
    parser.add_argument("--output-dir", default=str(DEFAULT_OUTPUT_DIR))
    parser.add_argument("--strict", action="store_true", help="fail if the profile's primary runtime port is not found")
    args = parser.parse_args()

    profile = resolve_profile(args.profile)
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    report = discover(profile)
    json_path = out_dir / "koalabyte_ports.json"
    env_path = out_dir / "koalabyte_ports.env"
    json_path.write_text(json.dumps(report, indent=2, sort_keys=True), encoding="utf-8")
    write_env(env_path, report["env"])  # type: ignore[arg-type]

    print(json.dumps({"profile": profile, "json": str(json_path), "env": str(env_path), "ports": report["ports"]}, indent=2, sort_keys=True))

    if args.strict:
        ports = report["ports"]  # type: ignore[assignment]
        primary = ports.get("primary_ble") if isinstance(ports, dict) else ""
        if not primary:
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())