#!/usr/bin/env python3
from __future__ import annotations

import argparse
import glob
import json
import os
import subprocess
import time
from pathlib import Path
from typing import Iterable

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_DIR = REPO_ROOT / "logs" / "preflight"

SERIAL_PATTERNS = (
    "/dev/serial/by-id/*",
    "/dev/ttyACM*",
    "/dev/ttyUSB*",
)

HELTEC_HINTS = (
    "heltec",
    "ht-n5262",
    "ht_n5262",
    "n5262",
    "wireless_tracker",
    "wireless-tracker",
)
ESP32_HINTS = (
    "espressif",
    "usb_jtag_serial_debug_unit",
    "usb-jtag",
    "usb_jtag",
    "serial_debug",
    "serial-debug",
    "esp32",
    "cp210",
    "ch340",
    "wchusb",
)
NRF_DONGLE_HINTS = (
    "pca10059",
    "nordic",
    "nrf52840_dongle",
    "nrf52840-dongle",
    "adafruit_nrf52840",
    "jlink",
)

STABLE_PATHS = {
    "heltec": "/dev/koalabyte-heltec",
    "heltec_t114_alias": "/dev/koalabyte-heltec-t114",
    "esp32_dualeye": "/dev/koalabyte-esp32-dualeye",
    "esp32_eyes": "/dev/koalabyte-esp32-eyes",
    "legacy_nrf": "/dev/koalabyte-nrf-ble",
}


def run(args: list[str], timeout: float = 3.0) -> dict[str, object]:
    try:
        proc = subprocess.run(args, capture_output=True, text=True, timeout=timeout, check=False)
        return {
            "command": args,
            "returncode": proc.returncode,
            "stdout": proc.stdout.strip(),
            "stderr": proc.stderr.strip(),
        }
    except (FileNotFoundError, subprocess.TimeoutExpired) as exc:
        return {"command": args, "returncode": 127, "stdout": "", "stderr": str(exc)}


def unique_paths(paths: Iterable[Path]) -> list[Path]:
    seen: set[str] = set()
    result: list[Path] = []
    for path in paths:
        value = str(path)
        if value not in seen:
            seen.add(value)
            result.append(path)
    return result


def serial_candidates() -> list[dict[str, str]]:
    paths: list[Path] = []
    for pattern in SERIAL_PATTERNS:
        paths.extend(Path("/").glob(pattern.lstrip("/")))
    entries: list[dict[str, str]] = []
    for path in unique_paths(sorted(paths)):
        try:
            resolved = str(path.resolve())
        except OSError:
            resolved = str(path)
        label = f"{path} {resolved}".lower()
        entries.append({"path": str(path), "resolved": resolved, "label": label})
    return entries


def has_any(label: str, hints: tuple[str, ...]) -> bool:
    return any(hint in label for hint in hints)


def choose_role(
    entries: list[dict[str, str]],
    hints: tuple[str, ...],
    avoid: set[str],
    stable_paths: tuple[str, ...] = (),
) -> str:
    for stable in stable_paths:
        if stable and Path(stable).exists() and stable not in avoid:
            return stable

    scored: list[tuple[int, str]] = []
    for entry in entries:
        path = entry["path"]
        resolved = entry["resolved"]
        label = entry["label"]
        if path in avoid or resolved in avoid:
            continue

        # Role-specific evidence is mandatory. A generic by-id or ttyACM path
        # alone must never classify an Espressif board as a Nordic dongle.
        if not has_any(label, hints):
            continue

        score = 100
        if path.startswith("/dev/serial/by-id/"):
            score += 25
        if "ttyacm" in label:
            score += 5
        if "ttyusb" in label:
            score += 3
        scored.append((score, path))

    if not scored:
        return ""
    scored.sort(key=lambda item: (-item[0], item[1]))
    return scored[0][1]


def add_avoid(entries: list[dict[str, str]], avoid: set[str], selected: str) -> None:
    if not selected:
        return
    avoid.add(selected)
    try:
        avoid.add(str(Path(selected).resolve()))
    except OSError:
        pass
    for entry in entries:
        if entry["path"] == selected or entry["resolved"] == selected:
            avoid.add(entry["path"])
            avoid.add(entry["resolved"])


def serial_id(path: str) -> str:
    return Path(path).name if path.startswith("/dev/serial/by-id/") else ""


def interface_exists(name: str) -> bool:
    return run(["ip", "link", "show", name])["returncode"] == 0


def write_env(path: Path, values: dict[str, str]) -> None:
    lines = ["# Generated by scripts/discover_koalabyte_ports.py"]
    for key, value in values.items():
        if value:
            safe = value.replace("'", "'\\''")
            lines.append(f"export {key}='{safe}'")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def discover(profile: str) -> dict[str, object]:
    entries = serial_candidates()
    avoid: set[str] = set()

    heltec = choose_role(
        entries,
        HELTEC_HINTS,
        avoid,
        (STABLE_PATHS["heltec_t114_alias"], STABLE_PATHS["heltec"]),
    )
    add_avoid(entries, avoid, heltec)

    esp32 = choose_role(
        entries,
        ESP32_HINTS,
        avoid,
        (STABLE_PATHS["esp32_dualeye"], STABLE_PATHS["esp32_eyes"]),
    )
    add_avoid(entries, avoid, esp32)

    legacy_nrf = choose_role(entries, NRF_DONGLE_HINTS, avoid, (STABLE_PATHS["legacy_nrf"],))
    primary_ble = heltec if profile == "heltec" else (legacy_nrf or heltec)

    can_interface = os.environ.get("CAN_INTERFACE", "can0")
    vcan_interface = os.environ.get("VCAN_INTERFACE", "vcan0")

    env = {
        "KOALABYTE_PRIMARY_BLE_PORT": primary_ble,
        "KOALABYTE_PRIMARY_BLE_SOURCE": "heltec-t114-nrf52840" if heltec else "legacy-nrf52840-dongle",
        "KOALABYTE_HELTEC_USB_PORT": heltec,
        "HELTEC_PORT": heltec,
        "HELTEC_MODEL": "Heltec_T114" if heltec else "",
        "HELTEC_USB_ID": serial_id(heltec),
        "KOALABYTE_HELTEC_T114_BY_ID": heltec if heltec.startswith("/dev/serial/by-id/") else "",
        "KOALABYTE_NRF_BLE_PORT": primary_ble,
        "NRF_BLE_PORT": primary_ble,
        "KOALABYTE_ESP32_FACE_PORT": esp32,
        "KOALABYTE_ESP32_MIC_PORT": esp32,
        "ESP32_PORT": esp32,
        "ESP32_DUALEYE_USB_ID": serial_id(esp32),
        "KOALABYTE_ESP32_DUALEYE_BY_ID": esp32 if esp32.startswith("/dev/serial/by-id/") else "",
        "CAN_INTERFACE": can_interface,
        "CAN_BITRATE": os.environ.get("CAN_BITRATE", "500000"),
        "VCAN_INTERFACE": vcan_interface,
    }

    return {
        "profile": profile,
        "timestamp": time.time(),
        "serial_candidates": entries,
        "stable_paths": STABLE_PATHS,
        "ports": {
            "primary_ble": primary_ble,
            "primary_ble_source": env["KOALABYTE_PRIMARY_BLE_SOURCE"],
            "heltec": heltec,
            "heltec_usb_id": serial_id(heltec),
            "legacy_nrf_ble": legacy_nrf,
            "esp32_eyes": esp32,
            "esp32_dualeye_usb_id": serial_id(esp32),
            "can_interface": can_interface,
            "can_present": interface_exists(can_interface),
            "vcan_interface": vcan_interface,
            "vcan_present": interface_exists(vcan_interface),
        },
        "env": env,
        "commands": {"lsusb": run(["lsusb"]), "ip_link": run(["ip", "link"])},
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Discover KoalaByte Blue USB and CAN roles.")
    parser.add_argument("--profile", choices=["main", "heltec", "auto"], default="heltec")
    parser.add_argument("--output-dir", default=str(DEFAULT_OUTPUT_DIR))
    parser.add_argument("--strict", action="store_true")
    args = parser.parse_args()

    profile = "heltec" if args.profile == "auto" else args.profile
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    report = discover(profile)
    json_path = output_dir / "koalabyte_ports.json"
    env_path = output_dir / "koalabyte_ports.env"
    json_path.write_text(json.dumps(report, indent=2, sort_keys=True), encoding="utf-8")
    write_env(env_path, report["env"])  # type: ignore[arg-type]
    print(json.dumps({"profile": profile, "json": str(json_path), "env": str(env_path), "ports": report["ports"]}, indent=2, sort_keys=True))

    ports = report["ports"]
    if args.strict and isinstance(ports, dict):
        if not ports.get("primary_ble") or not ports.get("esp32_eyes"):
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
