[platformio]
default_envs = esp32s3_dualeye

[env:esp32s3_dualeye]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_upload.flash_size = 16MB
board_build.flash_size = 16MB
board_build.partitions = huge_app.csv
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=1
  -DBOARD_HAS_PSRAM
  -DUSER_SETUP_LOADED
  -DGC9A01_DRIVER
  -DTFT_WIDTH=240
  -DTFT_HEIGHT=240
  -DTFT_MOSI=2
  -DTFT_SCLK=4
  -DTFT_CS=5
  -DTFT_DC=47
  -DTFT_RST=38
  -DTFT_BL=42
  -DTFT_BACKLIGHT_ON=LOW
  -DSPI_FREQUENCY=40000000
  -DSPI_READ_FREQUENCY=16000000
  -DTFT_RGB_ORDER=TFT_BGR
  -DTFT_INVERSION_ON
  -DLOAD_GLCD
  -DLOAD_FONT2
  -DLOAD_FONT4
  -DLOAD_FONT6
  -DLOAD_FONT7
  -DLOAD_FONT8
  -DLOAD_GFXFF
  -DSMOOTH_FONT
lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  h2zero/NimBLE-Arduino@^1.4.3
  bodmer/TFT_eSPI@^2.5.43
